locale = "en"
label = "English"
direction = "ltr"
weight = 1

title = "Robert Boscacci"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
dateFormat = "2 January 2006"

# mainSections = ["section1", "section2"]
# description = "My awesome website"

[params.author]
name = "Robert Boscacci"
image = "img/me.jpg"
headline = "Husband, Tinkerer, Things Done<br>☕👨‍💻🚲🍕🎥🎸😺🏕️"
bio = "I build useful systems, write when something sticks, and keep a few projects in motion."
links = [
  { github = "https://github.com/boscacci" },
  { linkedin = "https://linkedin.com/in/rboscacci" },
  { instagram = "https://www.instagram.com/cinemarob1/" },
]
