languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Robert Boscacci"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
dateFormat = "2 January 2006"

# mainSections = ["section1", "section2"]
# description = "My awesome website"

[params.author]
name = "Robert Boscacci"
image = "img/me.jpg"
headline = "Data Engineer from the Film Biz"
bio = "Cinema technician who learned to code"
links = [
  { github = "https://github.com/boscacci" },
  { linkedin = "https://linkedin.com/in/rboscacci" },
  { bluesky = "https://bsky.app/profile/robertboscacci.com" },
]
