[hugoVersion]
  extended = false
  min = "0.162.0"

[[mounts]]
  source = "archetypes"
  target = "archetypes"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "content"
  target = "content"

[[mounts]]
  source = "data"
  target = "data"

[[mounts]]
  source = "i18n"
  target = "i18n"

[[mounts]]
  source = "static"
  target = "static"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "themes/congo/layouts"
  target = "layouts"
