#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT_DIR="$ROOT_DIR/content"
MAP_FILE="$ROOT_DIR/outputs/external-media-map.tsv"
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage: scripts/apply_external_media_map.sh [options]

Replace externally hosted image file URLs in content with URLs from a migration
map generated by scripts/download_external_media.sh.

Options:
  --content-dir DIR  Content directory to update. Default: content
  --map-file FILE    TSV map file. Default: outputs/external-media-map.tsv
  --dry-run          Report replacements without editing files
  -h, --help         Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --content-dir)
      CONTENT_DIR="$2"
      shift 2
      ;;
    --map-file)
      MAP_FILE="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! -f "$MAP_FILE" ]]; then
  printf 'Map file not found: %s\n' "$MAP_FILE" >&2
  exit 2
fi

total=0

while IFS=$'\t' read -r original_url new_url _local_path; do
  [[ "$original_url" != "original_url" ]] || continue
  [[ -n "$original_url" && -n "$new_url" ]] || continue

  while IFS= read -r file; do
    [[ -n "$file" ]] || continue
    count="$(ORIGINAL_URL="$original_url" perl -0ne 'print scalar(() = /\Q$ENV{ORIGINAL_URL}\E/g)' "$file")"
    [[ "$count" -gt 0 ]] || continue
    total=$((total + count))

    if [[ "$DRY_RUN" -eq 0 ]]; then
      ORIGINAL_URL="$original_url" NEW_URL="$new_url" perl -0pi -e 's/\Q$ENV{ORIGINAL_URL}\E/$ENV{NEW_URL}/g' "$file"
    fi
  done < <(rg -l -F "$original_url" "$CONTENT_DIR" || true)
done < "$MAP_FILE"

if [[ "$DRY_RUN" -eq 1 ]]; then
  printf 'Would replace %s URL occurrence(s)\n' "$total"
else
  printf 'Replaced %s URL occurrence(s)\n' "$total"
fi
